fix ReferenceError
The variable hasn't been initialized, therefore in certain situations it could run into a
```
ReferenceError: parentForm is not defined
```